import { GroupType, Seat } from "../types/types";

export const WIDTH = 24;
export const HEIGHT = 9;

export const GROUPS: GroupType[] = [
  { name: "Madi.L", nb: 5, color: 'peru' },
  { name: "Leco.A", nb: 6, color: 'springgreen' },
  { name: "Maingu", nb: 2, color: 'aquamarine' },
  { name: "Bour.R", nb: 2, color: 'yellowgreen' },
  { name: "Coll.J", nb: 8, color: 'limegreen' },
  { name: "Meun.V", nb: 16, color: 'chocolate' },
  { name: "Leme.H", nb: 3, color: 'lavender' },
  { name: "Vall.M", nb: 2, color: 'moccasin' },
  { name: "Lero.E", nb: 2, color: 'saddlebrown' },
  { name: "Laur.T", nb: 8, color: 'white' },
  { name: "Jupin", nb: 2, color: 'palegoldenrod' },
  { name: "Pean.A", nb: 2, color: 'floralwhite' },
  { name: "Bett.A", nb: 9, color: 'salmon' },
  { name: "Pins.V", nb: 10, color: 'peachpuff' },
  { name: "Pott.N", nb: 2, color: 'green' },
  { name: "Remi p", nb: 3, color: 'coral' },
  { name: "Epro.I", nb: 6, color: 'mediumspringgreen' },
  { name: "Doue.K", nb: 1, color: 'lightsalmon' },
  { name: "Dilis", nb: 3, color: 'bisque' },
  { name: "Rondea", nb: 1, color: 'lavenderblush' },
  { name: "Delcou", nb: 4, color: 'antiquewhite' },
  { name: "Jarr.V", nb: 2, color: 'ivory' },
  { name: "Epro.M", nb: 5, color: 'orchid' },
  { name: "Gibon", nb: 6, color: 'lawngreen' },
  { name: "Lang.P  ", nb: 19, color: 'indianred' },
  { name: "Dane.D", nb: 2, color: 'crimson' },
  { name: "Techer", nb: 4, color: 'dimgray' },
  { name: "Pier.J", nb: 5, color: 'brown' },
  { name: "Pillai", nb: 7, color: 'cyan' },
  { name: "Less.B", nb: 1, color: 'floralwhite' },
  { name: "Yver.M", nb: 3, color: 'rosybrown' },
  { name: "Les vieux", nb: 33, color: 'steelblue' },
];

export const FORBIDDEN_SEATS: Seat[] = [
  { line: 1, col: 6},
  { line: 2, col: 6},
  { line: 3, col: 6},
  { line: 4, col: 6},
  { line: 5, col: 6},
  { line: 6, col: 6},
  { line: 7, col: 6},
  { line: 8, col: 6},
  { line: 1, col: 7},
  { line: 2, col: 7},
  { line: 3, col: 7},
  { line: 4, col: 7},
  { line: 5, col: 7},
  { line: 6, col: 7},
  { line: 7, col: 7},
  { line: 8, col: 7},
  { line: 1, col: 16},
  { line: 2, col: 16},
  { line: 3, col: 16},
  { line: 4, col: 16},
  { line: 5, col: 16},
  { line: 6, col: 16},
  { line: 7, col: 16},
  { line: 8, col: 16},
  { line: 1, col: 17},
  { line: 2, col: 17},
  { line: 3, col: 17},
  { line: 4, col: 17},
  { line: 5, col: 17},
  { line: 6, col: 17},
  { line: 7, col: 17},
  { line: 8, col: 17},
];