export const GROUPS = [
  { name: "Madi.L", nb: 5 },
  { name: "Leco.A", nb: 6 },
  { name: "Leco.A", nb: 6 },
  { name: "Maingu", nb: 2 },
  { name: "Bour.R", nb: 2 },
  { name: "Coll.J", nb: 8 },
  { name: "Meun.V", nb: 16 },
  { name: "Leme.H", nb: 3 },
  { name: "Vall.M", nb: 2 },
  { name: "Lero.E", nb: 2 },
  { name: "Laur.T", nb: 8 },
  { name: "Jupin", nb: 2 },
  { name: "Pean.A", nb: 2 },
  { name: "Bett.A", nb: 9 },
  { name: "Pins.V", nb: 10 },
  { name: "Pott.N", nb: 2 },
  { name: "Remi p", nb: 3 },
  { name: "Epro.I", nb: 6 },
  { name: "Doue.K", nb: 1 },
  { name: "Dilis", nb: 3 },
  { name: "Rondea", nb: 1 },
  { name: "Delcou", nb: 4 },
  { name: "Jarr.V", nb: 2 },
  { name: "Epro.M", nb: 5 },
  { name: "Gibon", nb: 6 },
  { name: "Lang.P  ", nb: 19 },
  { name: "Dane.D", nb: 2 },
  { name: "Techer", nb: 4 },
  { name: "Pier.J", nb: 5 },
  { name: "Pillai", nb: 7 },
  { name: "Less.B", nb: 1 },
  { name: "Yver.M", nb: 3 },
  { name: "Les vieux", nb: 33 },
];